library(here)
library(Zelig)
library(compiler)
library(psych)
library(LaplacesDemon)
library(MASS)
library(rmarkdown)
library(ezknitr)
library(cowplot)
library(ggpubr)
library(linguisticsdown)
library(summarytools)
library(gam)
library(tidyr)
library(ggplot2)
library(matrixStats)

cat("\n Welcome to Subsampling in Logistic Regression from Big Data.\n")
